language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel
  user: 6uhrmittag
  password:
    secure: "m5+zoXruA3XWWIJxGIHqlY6hT5hDTpN3ZxC1f80sk7o5S4t4i0etHgtXA+X+hEOEeUx4fXY0RXaUubJJlWa6GSHrJZZD7ne5Ig7tG06D0JmYQ0O9Y4xUl5e93diKcGBohnp6i+Y5IXJ7H3HVPCim4zgSzJbbLEimD+3H9IpOFH98I6qkDYT3c/QVCN8V8Uu1ZZi+e18uyUYj0SFR8FjQfKpyZK/VvkfE4f1O9UcYS/TMkoH3ZSmvrL9B69IwDEbgCl09Nd4YR7O5TRLdcwyM4ZcpVZAO/sjRRObk3qlhK6fAu3KNhkfK+TMBRz02DxeZP3Cw5V29W7eyq3VuzmqL3uu5u6kuj3fzabFPYan0LOYJxILbrhyKt7SZgdmoMdh2tAWmNcgRVaFGsXu3dociOXTkG7SjLgDLmHTWTEuuNDSpGdImggpoO4ajb7YTLYr9wrWraPy948VPN1lkB+i+0us3fRbIOCvFnQpCptS0UYXMLbY0vJhm3uQaiO5LLIIVI2121VYDeEPy7NH14Okrdn8KFM2c/8grzIwX/9dJ7gPBaQAwdPtGRKdgK9wKIFwGe9W2Bhw1cd2U9Bv3YXgElqj93c24Duhjh8VajP9bFYlbwIeID+F8SkjVUft/ii+iQWcYvtcokn3WHChB/vLAQGTFaQQynZt73GdyPkYDgDQ="
  on:
    tags: true
    repo: admindojo/admindojo-client
    python: 3.6
